### ISSUE TITLE
Modify folder and file PATH in the remote repository

### ISSUE THREAD

**Issue by yujinkim1** [yujinkim1/pricy-flutter-app#24]
```[tasklist]
### Tasks
- [ ] add .github folder 
- [ ] modify readmes folder path into .github/
- [ ] add .github/HISTORY.md
- [ ] move contents of Update history into .github/HISTORY.md
- [ ] add flutter manual
```

**위 tasklist 반영 후 synchronize 요청할 예정**

**Comment by yujinkim1** [comment]
### Completes
- [x] add .github folder 
- [x] modify readmes folder path into .github/
- [x] add .github/HISTORY.md
- [x] move contents of Update history into .github/HISTORY.md
- [x] add flutter manual
