### ISSUE TITLE
Flutter config is not reading from env file

### ISSUE THREAD

**Issue by yujinkim1** [yujinkim1/pricy-flutter-app#26]
```[tasklist]
### Task
- [ ] get certificate value from env file 
- [ ] Required by Flutter config
- [ ] Ensure Flutter config Iinitializer
- [ ] Load to env variable
```

**Comment by yujinkim1** [comment]
### Completes
- [x] get certificate value from env file 
- [x] Required by Flutter config
- [x] Ensure Flutter config Iinitializer
- [x] Load to env variable
